language: clojure
dist: bionic
lein: 2.9.1
sudo: required
before_install:
  - sudo apt-get -y install python3 python3-pip
  - sudo python3 -mpip install setuptools
  - sudo python3 -mpip install numpy
  - curl -O https://download.clojure.org/install/linux-install-1.10.2.796.sh
  - chmod +x linux-install-1.10.2.796.sh
  - sudo ./linux-install-1.10.2.796.sh
  - clojure -Sdescribe
addons:
  apt:
    update: true
install: clojure -Sdescribe
script: clojure -M:test
cache:
  directories:
    - "$HOME/.m2"
